"""MoveIt2 planning server for the Galaxea R1.

Isaac Lab runs on Python 3.10 (conda env ``galaxea-sim``) while ROS 2 Jazzy's
``moveit_py`` needs the system Python 3.12, so MoveIt cannot be imported inside
the simulation script. This server owns MoveIt and exposes planning over a
localhost TCP socket with one JSON object per line.

Run it with the system Python (ROS 2 Jazzy sourced), *not* isaaclab.sh:

    python3 source/standalone/galaxea/jinhern/9_moveit2_server.py

Protocol (one JSON request per line, one JSON response per line):

    {"type": "fk", "joint_state": {name: rad, ...}, "group": "left_arm",
     "tool_offset": [0, 0, 0.14]}
        -> {"success": true, "pose": [x, y, z, qw, qx, qy, qz]}

    {"type": "plan", "group": "left_arm", "joint_state": {...},
     "goal": [x, y, z, qw, qx, qy, qz], "tool_offset": [0, 0, 0.14],
     "obstacles": [{"name": "table", "position": [x, y, z],
                    "size": [dx, dy, dz]}]}
        -> {"success": true,
            "ee_poses": [[x, y, z, qw, qx, qy, qz], ...],
            "joint_names": [...], "joint_trajectory": [[...], ...],
            "times": [...]}

Poses are in the ``base_link`` frame (= robot base frame in Isaac).
``tool_offset`` is expressed in the flange frame, which coincides with
Isaac's ``left/right_arm_link6`` body frame; goals are given for the tool
point and returned ``ee_poses`` are tool points as well, so the client can
use them directly as IK-Abs action commands (offset 0.14, the IK action's
body_offset) or compare them with the ``*_ee_frame`` sensors (offset 0.15).
"""

import argparse
import itertools
import json
import os
import re
import socketserver

import numpy as np

# Generated by 9_moveit2_gen_urdf.py; kinematics match the Isaac USD asset.
DEFAULT_URDF = os.path.join(
    os.path.dirname(os.path.abspath(__file__)), "r1_from_usd.urdf"
)

GROUPS = {
    "left_arm": {
        "base_link": "base_link",
        "tip_link": "left_flange",
        "joints": [f"left_arm_joint{i}" for i in range(1, 7)],
    },
    "right_arm": {
        "base_link": "base_link",
        "tip_link": "right_flange",
        "joints": [f"right_arm_joint{i}" for i in range(1, 7)],
    },
}

# Match the Isaac actuator limits rather than the URDF's 20.9 rad/s so the
# time parameterization produces speeds the simulated robot can track.
MAX_VELOCITY = 2.175
MAX_ACCELERATION = 4.0


def build_srdf(urdf_text):
    robot_name = re.search(r"<robot\s+name=\"([^\"]+)\"", urdf_text).group(1)
    links = re.findall(r"<link\s+name=\"([^\"]+)\"", urdf_text)

    lines = [f'<robot name="{robot_name}">']
    for name, group in GROUPS.items():
        lines.append(f'  <group name="{name}">')
        lines.append(
            f'    <chain base_link="{group["base_link"]}"'
            f' tip_link="{group["tip_link"]}"/>'
        )
        lines.append("  </group>")

    # Self-collision checking is disabled for every link pair: the exported
    # meshes overlap at rest which would make every start state invalid.
    # Collision objects sent with a plan request are still checked.
    for a, b in itertools.combinations(links, 2):
        lines.append(
            f'  <disable_collisions link1="{a}" link2="{b}" reason="Default"/>'
        )
    lines.append("</robot>")
    return "\n".join(lines)


def build_moveit_config(urdf_text):
    srdf_text = build_srdf(urdf_text)
    joint_limits = {}
    for group in GROUPS.values():
        for joint in group["joints"]:
            joint_limits[joint] = {
                "has_velocity_limits": True,
                "max_velocity": MAX_VELOCITY,
                "has_acceleration_limits": True,
                "max_acceleration": MAX_ACCELERATION,
            }
    return {
        "robot_description": urdf_text,
        "robot_description_semantic": srdf_text,
        "robot_description_kinematics": {
            name: {
                "kinematics_solver": "kdl_kinematics_plugin/KDLKinematicsPlugin",
                "kinematics_solver_search_resolution": 0.005,
                "kinematics_solver_timeout": 0.05,
            }
            for name in GROUPS
        },
        "robot_description_planning": {"joint_limits": joint_limits},
        "planning_pipelines": {"pipeline_names": ["ompl"]},
        "plan_request_params": {
            "planning_pipeline": "ompl",
            "planning_time": 5.0,
            "planning_attempts": 3,
            "max_velocity_scaling_factor": 1.0,
            "max_acceleration_scaling_factor": 1.0,
        },
        "ompl": {
            "planning_plugins": ["ompl_interface/OMPLPlanner"],
            "request_adapters": [
                "default_planning_request_adapters/ResolveConstraintFrames",
                "default_planning_request_adapters/ValidateWorkspaceBounds",
                "default_planning_request_adapters/CheckStartStateBounds",
                "default_planning_request_adapters/CheckStartStateCollision",
            ],
            "response_adapters": [
                "default_planning_response_adapters/AddTimeOptimalParameterization",
                "default_planning_response_adapters/ValidateSolution",
            ],
            "start_state_max_bounds_error": 0.1,
        },
    }


def matrix_to_quat_wxyz(matrix):
    """Convert a 3x3 rotation matrix to a (w, x, y, z) quaternion."""
    m = matrix
    trace = m[0, 0] + m[1, 1] + m[2, 2]
    if trace > 0.0:
        s = 2.0 * np.sqrt(trace + 1.0)
        w = 0.25 * s
        x = (m[2, 1] - m[1, 2]) / s
        y = (m[0, 2] - m[2, 0]) / s
        z = (m[1, 0] - m[0, 1]) / s
    elif m[0, 0] > m[1, 1] and m[0, 0] > m[2, 2]:
        s = 2.0 * np.sqrt(1.0 + m[0, 0] - m[1, 1] - m[2, 2])
        w = (m[2, 1] - m[1, 2]) / s
        x = 0.25 * s
        y = (m[0, 1] + m[1, 0]) / s
        z = (m[0, 2] + m[2, 0]) / s
    elif m[1, 1] > m[2, 2]:
        s = 2.0 * np.sqrt(1.0 + m[1, 1] - m[0, 0] - m[2, 2])
        w = (m[0, 2] - m[2, 0]) / s
        x = (m[0, 1] + m[1, 0]) / s
        y = 0.25 * s
        z = (m[1, 2] + m[2, 1]) / s
    else:
        s = 2.0 * np.sqrt(1.0 + m[2, 2] - m[0, 0] - m[1, 1])
        w = (m[1, 0] - m[0, 1]) / s
        x = (m[0, 2] + m[2, 0]) / s
        y = (m[1, 2] + m[2, 1]) / s
        z = 0.25 * s
    quat = np.array([w, x, y, z])
    return quat / np.linalg.norm(quat)


def quat_wxyz_to_matrix(quat):
    w, x, y, z = np.asarray(quat, dtype=float) / np.linalg.norm(quat)
    return np.array(
        [
            [1 - 2 * (y * y + z * z), 2 * (x * y - w * z), 2 * (x * z + w * y)],
            [2 * (x * y + w * z), 1 - 2 * (x * x + z * z), 2 * (y * z - w * x)],
            [2 * (x * z - w * y), 2 * (y * z + w * x), 1 - 2 * (x * x + y * y)],
        ]
    )


class R1Planner:
    def __init__(self, urdf_path):
        from moveit.planning import MoveItPy
        # Imported for their side effect: registering the pybind11 types that
        # get_robot_model() and joint_positions return.
        import moveit.core.robot_model  # noqa: F401
        import moveit.core.robot_state  # noqa: F401

        with open(urdf_path) as f:
            urdf_text = f.read()
        self.moveit = MoveItPy(
            node_name="r1_moveit_py", config_dict=build_moveit_config(urdf_text)
        )
        self.robot_model = self.moveit.get_robot_model()

    def _make_state(self, joint_state):
        from moveit.core.robot_state import RobotState

        state = RobotState(self.robot_model)
        state.set_to_default_values()
        # Any joint the MoveIt model knows (arms, torso, ...) is taken from the
        # request; everything else (e.g. Isaac's gripper axes) is ignored.
        positions = state.joint_positions
        for name, value in joint_state.items():
            if name in positions:
                positions[name] = float(value)
        state.joint_positions = positions
        state.update()
        return state

    def _tool_pose(self, state, tip_link, tool_offset):
        transform = np.asarray(state.get_global_link_transform(tip_link))
        rotation = transform[:3, :3]
        position = transform[:3, 3] + rotation @ np.asarray(tool_offset)
        quat = matrix_to_quat_wxyz(rotation)
        return [*(float(v) for v in position), *(float(v) for v in quat)]

    def fk(self, request):
        group = GROUPS[request.get("group", "left_arm")]
        state = self._make_state(request["joint_state"])
        tool_offset = request.get("tool_offset", [0.0, 0.0, 0.0])
        return {"success": True, "pose": self._tool_pose(state, group["tip_link"], tool_offset)}

    def _apply_obstacles(self, obstacles):
        from moveit_msgs.msg import CollisionObject
        from shape_msgs.msg import SolidPrimitive
        from geometry_msgs.msg import Pose

        with self.moveit.get_planning_scene_monitor().read_write() as scene:
            scene.remove_all_collision_objects()
            for obstacle in obstacles:
                box = CollisionObject()
                box.header.frame_id = self.robot_model.model_frame
                box.id = obstacle["name"]
                primitive = SolidPrimitive()
                primitive.type = SolidPrimitive.BOX
                primitive.dimensions = [float(v) for v in obstacle["size"]]
                pose = Pose()
                pose.position.x = float(obstacle["position"][0])
                pose.position.y = float(obstacle["position"][1])
                pose.position.z = float(obstacle["position"][2])
                pose.orientation.w = 1.0
                box.primitives.append(primitive)
                box.primitive_poses.append(pose)
                box.operation = CollisionObject.ADD
                scene.apply_collision_object(box)

    def plan(self, request):
        from geometry_msgs.msg import PoseStamped

        group_name = request.get("group", "left_arm")
        group = GROUPS[group_name]
        tool_offset = np.asarray(request.get("tool_offset", [0.0, 0.0, 0.0]))

        self._apply_obstacles(request.get("obstacles", []))

        start_state = self._make_state(request["joint_state"])

        # The goal is given for the tool point; convert it to the tip link.
        goal = request["goal"]
        rotation = quat_wxyz_to_matrix(goal[3:7])
        tip_position = np.asarray(goal[0:3]) - rotation @ tool_offset

        goal_pose = PoseStamped()
        goal_pose.header.frame_id = self.robot_model.model_frame
        goal_pose.pose.position.x = float(tip_position[0])
        goal_pose.pose.position.y = float(tip_position[1])
        goal_pose.pose.position.z = float(tip_position[2])
        goal_pose.pose.orientation.w = float(goal[3])
        goal_pose.pose.orientation.x = float(goal[4])
        goal_pose.pose.orientation.y = float(goal[5])
        goal_pose.pose.orientation.z = float(goal[6])

        component = self.moveit.get_planning_component(group_name)
        component.set_start_state(robot_state=start_state)
        component.set_goal_state(
            pose_stamped_msg=goal_pose, pose_link=group["tip_link"]
        )
        result = component.plan()
        if not result:
            return {"success": False, "error": "planning failed"}

        trajectory_msg = result.trajectory.get_robot_trajectory_msg()
        joint_names = list(trajectory_msg.joint_trajectory.joint_names)

        ee_poses = []
        joint_trajectory = []
        times = []
        state = self._make_state(request["joint_state"])
        for point in trajectory_msg.joint_trajectory.points:
            positions = state.joint_positions
            for name, value in zip(joint_names, point.positions):
                positions[name] = float(value)
            state.joint_positions = positions
            state.update()
            ee_poses.append(self._tool_pose(state, group["tip_link"], tool_offset))
            joint_trajectory.append([float(v) for v in point.positions])
            times.append(
                point.time_from_start.sec + point.time_from_start.nanosec * 1e-9
            )

        return {
            "success": True,
            "ee_poses": ee_poses,
            "joint_names": joint_names,
            "joint_trajectory": joint_trajectory,
            "times": times,
        }

    def handle(self, request):
        try:
            if request.get("type") == "fk":
                return self.fk(request)
            if request.get("type") == "plan":
                return self.plan(request)
            return {"success": False, "error": f"unknown type {request.get('type')}"}
        except Exception as error:  # noqa: BLE001 - report to the client
            return {"success": False, "error": f"{type(error).__name__}: {error}"}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--urdf", default=DEFAULT_URDF)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8765)
    args = parser.parse_args()

    planner = R1Planner(args.urdf)

    class Handler(socketserver.StreamRequestHandler):
        def handle(self):
            for line in self.rfile:
                line = line.strip()
                if not line:
                    continue
                response = planner.handle(json.loads(line))
                self.wfile.write(json.dumps(response).encode() + b"\n")
                self.wfile.flush()

    class Server(socketserver.ThreadingTCPServer):
        allow_reuse_address = True

    with Server((args.host, args.port), Handler) as server:
        print(f"[9_moveit2_server] planning server listening on {args.host}:{args.port}")
        server.serve_forever()


if __name__ == "__main__":
    main()